### ISSUE TITLE
SNOW-403403: runtime error: invalid memory address or nil pointer dereference when inserting into a temporary table via Array

### ISSUE THREAD

**Issue by dhan-yext** [snowflakedb/gosnowflake#456] opened 2021-07-23 18:21 UTC
### Issue description
We're trying to insert batches of 1 million uuids into a temporary table via Array. The first batch successfully inserts, but upon calling ExecContext to insert the second, we get the following error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x458 pc=0x191954b]

Right before the panic occurs, the snowflake db connection is open and not nil, and the max idle time and max lifetime are both 0:

&{waitDuration:0 connector:{dsn:DEV_SERVICE:<password>@<account>.us-east-1/DEV_PLATFORM/LOGS?warehouse=DEV_WORKFLOW&role=DEV_API_GATEWAY driver:0x279f6c8} numClosed:0 mu:{state:0 sema:0} freeConn:[0xc0000d2c60] connRequests:map[] nextRequest:0 numOpen:1 openerCh:0xc000116cc0 closed:false dep:map[0xc0000d2c60:map[0xc0000d2c60:true]] lastPut:map[] maxIdleCount:0 maxOpen:0 maxLifetime:0 maxIdleTime:0 cleanerCh:<nil> waitCount:0 maxIdleClosed:0 maxIdleTimeClosed:0 maxLifetimeClosed:0 stop:0x10a3480}

### Example code
```go
        mil := 1000000
	uuids := make([]string, mil)
	for i := 0; i < mil; i++ {
		uuids[i] = "017ad203-66ac-9147-398b-39860e77b3ba"
	}
	db := snowflake.SnowflakeConn()
	randTableNum := rand.Intn(10000)
	tempTableName := fmt.Sprintf("LOGS.%s_REQUESTS_UUIDS_%d", "api", randTableNum)
        ctx := context.Background()
	_, err = db.ExecContext(ctx, fmt.Sprintf(
		"CREATE TEMPORARY TABLE %s (UUID VARCHAR(64) NOT NULL)", tempTableName))

	for i := 0; i < 3; i++ {
		err := db.Ping()
		if err != nil {
			glog.Errorf("error pinging conn", err)
		}
		_, err = db.ExecContext(ctx,
			fmt.Sprintf("INSERT INTO %s VALUES ", tempTableName)+"(?)", gosnowflake.Array(&uuids))
		glog.FatalIf(err)
	}
```

### Error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x458 pc=0x191954b]

goroutine 1 [running]:
github.com/snowflakedb/gosnowflake.(*bindUploader).createStageIfNeeded(0xc0034f8948, 0x110fcf6, 0x1cd5440)
	external/com_github_snowflakedb_gosnowflake/bind_uploader.go:92 +0xab
github.com/snowflakedb/gosnowflake.(*bindUploader).uploadStreamInternal(0xc0034f8948, 0xc0000ee000, 0x1, 0x30, 0x25, 0x0)
	external/com_github_snowflakedb_gosnowflake/bind_uploader.go:64 +0x45
github.com/snowflakedb/gosnowflake.(*bindUploader).upload(0xc0034f8948, 0xc00043b890, 0x1, 0x1, 0x24, 0xc0002822c0, 0x31)
	external/com_github_snowflakedb_gosnowflake/bind_uploader.go:53 +0x1b7
github.com/snowflakedb/gosnowflake.(*snowflakeConn).exec(0xc00058e060, 0x20ba758, 0xc00043b950, 0xc0132c4880, 0x3d, 0xc000000000, 0xc00043b890, 0x1, 0x1, 0x0, ...)
	external/com_github_snowflakedb_gosnowflake/connection.go:126 +0x1157
github.com/snowflakedb/gosnowflake.(*snowflakeConn).ExecContext(0xc00058e060, 0x20ba6e8, 0xc00012a000, 0xc0132c4880, 0x3d, 0xc00043b890, 0x1, 0x1, 0x2292164, 0x2a, ...)
	external/com_github_snowflakedb_gosnowflake/connection.go:306 +0x2cb
database/sql.ctxDriverExec(0x20ba6e8, 0xc00012a000, 0xbeada98, 0xc00058e060, 0x0, 0x0, 0xc0132c4880, 0x3d, 0xc00043b890, 0x1, ...)
	GOROOT/src/database/sql/ctxutil.go:31 +0x22e
database/sql.(*DB).execDC.func2()
	GOROOT/src/database/sql/sql.go:1577 +0x1df
database/sql.withLock(0x20aa1f8, 0xc0000d2c60, 0xc001c4bbd8)
	GOROOT/src/database/sql/sql.go:3294 +0x69
database/sql.(*DB).execDC(0xc0002a60d0, 0x20ba6e8, 0xc00012a000, 0xc0000d2c60, 0xc001c4bd00, 0xc0132c4880, 0x3d, 0xc0034f9e98, 0x1, 0x1, ...)
	GOROOT/src/database/sql/sql.go:1572 +0x495
database/sql.(*DB).exec(0xc0002a60d0, 0x20ba6e8, 0xc00012a000, 0xc0132c4880, 0x3d, 0xc001c4be98, 0x1, 0x1, 0x1, 0xc0132c4880, ...)
	GOROOT/src/database/sql/sql.go:1557 +0x13c
database/sql.(*DB).ExecContext(0xc0002a60d0, 0x20ba6e8, 0xc00012a000, 0xc0132c4880, 0x3d, 0xc0034f9e98, 0x1, 0x1, 0x20afd10, 0xc0002f49c0, ...)
	GOROOT/src/database/sql/sql.go:1535 +0xe5
```

### Configuration
*Driver version (or git SHA):* v1.6.0

*Go version:* go1.16.5 darwin/amd64

*Server version:* 5.29.1

*Client OS:* macOS Catalina 10.15.7

**Comment by sfc-gh-jbahk** [comment] 2021-07-27 20:04
@dhan-yext Hello, I've been able to reproduce this but it's a little unclear why you've inserted the same array 3 times. The insertion is successful on my end on the first loop. Could you provide more details? Thanks.

**Comment by sfc-gh-jbahk** [comment] 2021-07-27 20:07
Actually, I see that was the intended behavior in the first place. I will keep this thread open and circle back with updates - thanks.

**Comment by sfc-gh-jbahk** [comment] 2021-08-06 16:30
@dhan-yext We are working on this issue and will provide an update soon.

**Comment by sfc-gh-jbahk** [comment] 2021-08-09 21:17
@dhan-yext This has been addressed, fixed and merged. It will be available in the next release. Thank you.

**Closed** 2021-08-17 19:42 UTC
