### ISSUE TITLE
SNOW-636822: Bulk write Array Bind: Support NULL values

### ISSUE THREAD

**Issue by ralphtj** [snowflakedb/gosnowflake#633] opened 2022-07-28 17:26 UTC
### Issue description
I am trying to do bulk insert using the method provided in the documentation. Would like to inserts null values

I referred the documentation for bulk array bind.
// Create a table containing an integer, float, boolean, and string column.
_, err = db.Exec("create or replace table my_table(c1 int, c2 float, c3 boolean, c4 string)")
...
// Define the arrays containing the data to insert.
intArray := []int{1, 2, 3}
fltArray := []float64{0.1, 2.34, 5.678}
boolArray := []bool{true, false, true}
strArray := []string{"test1", "test2", "test3"}
...
// Insert the data from the arrays and wrap in an Array() function into the table.
_, err = db.Exec("insert into my_table values (?, ?, ?, ?)", Array(&intArray), Array(&fltArray), Array(&boolArray), Array(&strArray))

I modified the code the use sql.Null data types or interface, but getting error.

### Example code
```go
func arrayWriteFail(db *sql.DB) {
	ids := make([]sql.NullInt64, 3)
	ids[0] = sql.NullInt64{100, true}

	updTimes := []time.Time{time.Now(), time.Now(), time.Now()}

	_, err := db.Exec("CREATE OR REPLACE TABLE test.public.test_array_bind_2(id int, timestamp timestamptz)")
	if err != nil {
		fmt.Println("create table error", err)
		return
	}
	_, err = db.Exec("insert into test.public.test_array_bind_2(id, timestamp) values (?, ?)", sf.Array(&ids), sf.Array(&updTimes, sf.TimestampLTZType))
	if err != nil {
		fmt.Println("exec error", err)
		return
	}
	fmt.Println("err", err)
}

func interfaceArrayWriteFail(db *sql.DB) {
	ids := make([]interface{}, 3)
	ids[0] = 100

	updTimes := []time.Time{time.Now(), time.Now(), time.Now()}

	_, err := db.Exec("CREATE OR REPLACE TABLE test.public.test_array_bind_3(id int, timestamp timestamptz)")
	if err != nil {
		fmt.Println("create table error", err)
		return
	}
	_, err = db.Exec("insert into test.public.test_array_bind_3(id, timestamp) values (?, ?)", sf.Array(&ids), sf.Array(&updTimes, sf.TimestampLTZType))
	if err != nil {
		fmt.Println("exec error", err)
		return
	}
	fmt.Println("err", err)
}
```

### Error log
```
exec error sql: converting argument $1 type: unsupported type []sql.NullInt64, a slice of struct
exec error sql: converting argument $1 type: unsupported type []interface {}, a slice of interface
```
Add ``glog` option to your application to collect log files.

### Configuration
*Driver version (or git SHA):*

*Go version:* go1.18.3

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
6.25.0
```

*Client OS:* Mac 12.2.1

**Comment by sfc-gh-dszmolka** [comment] 2023-03-28 15:40
hi, thank you for raising this issue with us and providing such details!

it seems to be resolved with the newer versions of the driver, at least i tested now with the `v1.6.16` version of the driver, by simply copy/pasting `interfaceArrayWriteFail` definition and running it. It did not produce any error and in fact when querying the test table after running the INSERT:
```sql
ID	TIMESTAMP
100	2023-03-28 08:33:18.345 -0700
*	2023-03-28 08:33:18.345 -0700
*	2023-03-28 08:33:18.345 -0700
```
(using asterisk `*` to visualize the `null` values here which have been inserted)

i also see that the documentation at https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Binding_Parameters_to_Array_Variables addresses this use case and specifically mentions `v1.6.12` as the supported version, so should work with that version or later.  therefore closing this issue.

if you still face this issue with the latest `gosnowflake` versions, could you please post a reproduction code snippet, or even better a full minimal program which when run, exhibits the issue ? thank you in advance!

**Closed by sfc-gh-dszmolka** 2023-03-28 15:40 UTC
