### ISSUE TITLE
SNOW-545648: Unintuitive timezone behavior, lack of documentation

### ISSUE THREAD

**Issue by kevin-lindsay-1** [snowflakedb/gosnowflake#550] opened 2022-02-17 17:54 UTC
If you create a `time.Now()` using `DataTypeTimestampLtz`, this driver doesn't appear to work correctly.

I don't really know what it was doing under the hood, but it was definitely detecting the wrong timezone.

As far as I'm concerned it doesn't work; I set the logger to debug and it didn't look like it was formatting the value correctly (or at all).

I'm not using this behavior because it appears to not work, and it does unintuitive things like automatic timezone detection. I don't know why I would need that behavior, but regardless it doesn't appear to work.

I'm not going to follow up on this issue. Feel free to ack and close.

**Comment by sfc-gh-jbahk** [comment] 2022-02-17 19:01
@kevin-lindsay-1 Thank you for bringing this to our attention. Would you mind sharing how you're using DataTypeTimestampLtz? Whether it be a bug or lack of documentation, we'd like to fix this problem. Thanks.

**Comment by sfc-gh-jbahk** [comment] 2022-02-17 19:19
I see. Timestamp_LTZ is meant to capture the current session's timezone, noted in the TIMEZONE session parameter. We will look into what went wrong here.

**Comment by kevin-lindsay-1** [comment] 2022-02-17 19:24
Yeah I was more referring to "I don't understand why you're capturing a timezone when UTC exists and you can just convert the value to UTC".

**Comment by sfc-gh-dszmolka** [comment] 2023-03-28 11:34
linked issue #555 was resolved by PR #571 so closing this as resolved too. 
if you found the issue is unrelated to what was resolved in the referenced PR and/or it is still an issue for you, please reopen it with the details or comment and I'll reopen it for you. thank you !

**Closed by sfc-gh-dszmolka** 2023-03-28 11:34 UTC
