### ISSUE TITLE
SNOW-274063: QueryRowContext an QueryContext hang when use with WithRequestID

### ISSUE THREAD

**Issue by tjdavis3** [snowflakedb/gosnowflake#373] opened 2021-01-29 16:18 UTC
### Issue description
Query should run using the passed Query ID.  If QueryRowContext is run with a context.Background() it works fine.  However, if run with the WithRequestID context it hangs on the query.

### Example code
```go
	db, err := sql.Open("snowflake", connectionString)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	ctx := context.Background()
	ctxWithID := snowflake.WithRequestID(ctx, "123-456-6655")
	fmt.Println("running query")
	// row = db.QueryRowContext(ctx, "SELECT 1;")
	row := db.QueryRowContext(ctxWithID, "select 1;")
	if err = row.Err(); err != nil {
		log.Fatal(err)
	}
	fmt.Println("success")
```

### Error log
Hangs at query

### Configuration
*Driver version (or git SHA):* v1.3.13

*Go version:* go version go1.15.2 darwin/amd64

*Server version:* 5.2.2

*Client OS:* MacOS 10.15.7 (Catalina)

**Comment by sfc-gh-dwu** [comment] 2021-02-02 23:09
If the request ID is instead of UUID format, does your query still get stuck?
For example, instead of `123-456-6655`, if the request ID given were proper UUIDs `7c52678a-65ab-11eb-ae93-0242ac130002`?

I think there is still a bug here with how we are propagating the query error, if the request ID is malformed, then `row.Err()` should be non-nil vs being hung indefinitely.

**Comment by sfc-gh-dwu** [comment] 2021-02-03 00:58
Reproduced the error, the hang is due to the http retry logic kicking in even for HTTP_400 status return code, so it's stuck retrying a bad request (due to the request ID needing to be a valid UUID)

**Comment by tjdavis3** [comment] 2021-02-03 02:59
I did confirm that using a UUID does allow the call to work.  However, snowflake does not appear to be using it as the query ID.  My use case is to determine the QueryID so that I can use the caching functionality.  Since the resulting queryID is not exported I was attempting to preset the query ID, which is what I thought this meant in the docs:

> Query request ID ¶
> Specific query request ID can be set in the context and will be passed through in place of the default randomized request ID. For example:
>
> ```golang
> ctxWithID := WithRequestID(ctx, "app-request-id-...")
> rows, err := db.QueryContext(ctxWithID, query)
> ```

**Comment by sfc-gh-dwu** [comment] 2021-02-03 03:03
The Query ID is different from the user-specified Request ID.
The Request ID is really only used for logging and auditing purposes.
The query id that you are referring to is our internal system generated identifier for the job and can't be overridden by the caller.

**Comment by tjdavis3** [comment] 2021-02-03 13:51
Any chance of getting the QueryID exported?  I see it in the response and rows structs, but I cannot find a way to retrieve it other than issuing another query for last_query_id() which seems inefficient.

**Comment by ralfbecher** [comment] 2021-02-18 22:02
Maybe snowflakeRows could expose queryID..

**Comment by mysticmode** [comment] 2021-02-26 10:43
I'm wondering, what is the purpose of this [PR - Emit Query ID](https://github.com/snowflakedb/gosnowflake/pull/370) since it gets merged.

I suppose, the issue is that the `*snowflakeRows` is not exported in [query.go](https://github.com/snowflakedb/gosnowflake/blob/master/query.go#L81) hence we are facing this issue where the Query ID is not getting exposed.

**Comment by mysticmode** [comment] 2021-02-26 12:51
I was wrong in saying that the `*snowflakeRows` should be exported. I checked the master branch of this repository and the query ID gets emitted correctly when I use `WithQueryIDChan()` via `AsyncMode()`.

**Comment by sfc-gh-jbahk** [comment] 2021-02-26 23:53
Hi @tjdavis3 and @ralfbecher , as @mysticmode points out, as per the Golang release v1.4.1, you can use `WithQueryIDChan` to retrieve the query ID before the completion of the query.

**Comment by ralfbecher** [comment] 2021-02-27 10:22
Thanks, did you meant as per the gosnowflake release v1.4.1?

**Comment by sfc-gh-jbahk** [comment] 2021-02-28 05:15
@ralfbecher yes, that is correct

**Closed** 2021-03-02 12:45 UTC
