### ISSUE TITLE
SNOW-1011471 Authentication failed when setting search_path parameter on connection string

### ISSUE THREAD

**Issue by mattj150** [snowflakedb/gosnowflake#1034] opened 2024-01-17 23:15 UTC
What version of GO driver are you using? 1.7.0

    What operating system and processor architecture are you using? M1 Macbook pro

    What version of GO are you using? 1.21.4

    Server version: 7.43.0

    What did you do?

I'm attempting to set the snowflake search_path session parameter as part of my connection string when running sql.Open(). When I add this parameter to the end of the connection string I get "Authentication Failed". If i remove this parameter the authentication succeeds. The logs show the correct parameter in the query string. 

Example code: 

```go
connectionString := fmt.Sprintf("%s:%s@%s?&warehouse=%s&role=%s&search_path=$current", c.Config.Username, c.Config.Password, c.Config.Account, c.Config.Warehouse, c.Config.Role)
db, err := sql.Open("snowflake", connectionString)
if err != nil {
  return fmt.Errorf("could not connect to snowflake: %v", err)
}
```

Debug Logs: 
```
INFO[0002]log.go:216 gosnowflake.(*defaultLogger).Info Open
INFO[0002]log.go:154 gosnowflake.(*defaultLogger).Infof Query String: &warehouse=XX&role=XX&search_path=$current
INFO[0002]log.go:216 gosnowflake.(*defaultLogger).Info OpenWithConfig
INFO[0002]log.go:154 gosnowflake.(*defaultLogger).Infof Authenticating via SNOWFLAKE
INFO[0002]auth.go:353 gosnowflake.authenticate PARAMS for Auth: &map[roleName:[XX] warehouse:[XX]], https,XX.snowflakecomputing.com, 443, 5m0s, SNOWFLAKE
INFO[0002]log.go:154 gosnowflake.(*defaultLogger).Infof full URL: https://XX.snowflakecomputing.com:443/session/v1/login-request?requestId=XX&request_guid=XX&roleName=XX&warehouse=XX
INFO[0002]retry.go:285 gosnowflake.(*retryHTTP).execute retryHTTP.totalTimeout: 5m0s
DEBU[0002]log.go:148 gosnowflake.(*defaultLogger).Debugf retry count: 0
INFO[0002]log.go:216 gosnowflake.(*defaultLogger).Info Username and password
INFO[0002]log.go:154 gosnowflake.(*defaultLogger).Infof Subject: CN=*.va3.us-east-1.snowflakecomputing.com, Issuer: CN=Amazon RSA 2048 M02,O=Amazon,C=US
INFO[0002]log.go:154 gosnowflake.(*defaultLogger).Infof Subject: CN=Amazon RSA 2048 M02,O=Amazon,C=US, Issuer: CN=Amazon Root CA 1,O=Amazon,C=US
ERRO[0002]log.go:352 gosnowflake.(*defaultLogger).Errorln Authentication FAILED
```

**Comment by sfc-gh-dszmolka** [comment] 2024-01-22 06:52
hi and thank you for submitting this issue - thanks to all the details you provided, I reproduced the same problem. 

However, I do not think it is anyhow related to the Snowflake Go driver; since the exact same behaviour reproduces with the Python driver as well:
```pyhon
import snowflake.connector


con = snowflake.connector.connect(
    user='admin',
    account='myaccount.eu-central-1',
    password='password',
    database='TEST_DB',
    schema='PUBLIC',
    session_parameters={ "SEARCH_PATH": "'$current'" }
)

print(con.cursor().execute("select current_user()").fetchall())
con.close()
```

crashes the exact same way, producing very similar output to that of `gosnowflake`'s:
```
ERRO[0085]log.go:352 gosnowflake.(*defaultLogger).Errorln Authentication FAILED                        
2024/01/22 04:55:44 failed to run a query. SELECT 1, err: 370001 (08004): Internal error: Processing aborted due to error 300002:1428825699; incident 4650476.
```

suggesting something goes wrong inside the Snowflake engine, rather than the driver. 

I now passed the details found during the investigation on to the team responsible for the Snowflake engine to investigate further. 

While it gets sorted, you can perhaps consider setting up a [multi-statement query](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Executing_Multiple_Statements_in_One_Call) as a workaround and after authenticating without `SEARCH_PATH` session parameter, fire it as the first query in the multi-statement, something like:
```go
multi_statement_query := "ALTER SESSION SET SEARCH_PATH='$current'; SELECT 1;"
```
[example program for multi-statement queries](https://github.com/snowflakedb/gosnowflake/blob/master/cmd/multistatement/multistatement.go)

tested it and specifying it inside the multi-statement query did not crash it. 

Hope it helps you too. For this issue, I'm going to close it since it does not seem to be related to the `gosnowflake` driver but rather the backend does not seem to support `SEARCH_PATH` as part of the connection string.

**Closed** 2024-01-22 06:52 UTC
Labels: bug, wontfix

**Comment by mattj150** [comment] 2024-01-22 16:55
Thanks for the clarification on this. 

Would you have any recommendations/work around on running ALTER SESSION every time a new connection is added to the connection pool? I'd prefer to set the search path only once after I run db.Open() instead of having to set it on every SQL query in my code.

**Comment by sfc-gh-dszmolka** [comment] 2024-01-22 17:11
perhaps you could try using context, example from insertvariantobject.go from over the example programs here (many others use the same approach)
```go
	db, err := sql.Open("snowflake", dsn)
	if err != nil {
		log.Fatalf("failed to connect. %v, err: %v", dsn, err)
	}
	defer db.Close()

	ctx := context.Background()
	conn, err := db.Conn(ctx)
	if err != nil {
		log.Fatalf("Failed to acquire connection. err: %v", err)
	}
	defer conn.Close()
```

per [sql.DB.Conn](https://pkg.go.dev/database/sql#DB.Conn) documentation, this way a pool is used and thus the same session for all the subsequent commands = same `ALTER SESSION..` should affect all subsequent commands in the same session.

Alternatively perhaps since the param seems to be account lineage (Can be set for Account » User » Session), if that makes sense to your use case, you can 'hardcode' it even for one or more users with
`ALTER USER <username> SET SEARCH_PATH = '<value...>' `

then it will be the default for the particular user, without needing to set it always.
