### ISSUE TITLE
A question about Heartbeat implementation

### ISSUE THREAD

**Issue by ilkinulas** [snowflakedb/gosnowflake#181] opened 2018-08-07 16:56 UTC
### Issue description
When `CLIENT_SESSION_KEEP_ALIVE` is enabled, snowflake go  driver starts a heartbeat goroutine every time `func (sc *snowflakeConn) exec(.....)` is called. It only stops the heartbeat when `Close()` is called on the connection.

If you send multiple queries without closing the connection, snowflake go driver leaks goroutines.

In the example below the same connection is used to create and query a temporary table. This example starts 6 heartbeat goroutines but stops only one.

Is this the expected behavior?

### Example code
```go
func Test_KeepAlive(t *testing.T) {
	db, err := NewConnection(NewSnowflakeConfig())
	assertNoError(t, err)
	defer db.Close()

	db.Exec(`create temporary table my_temp_table (col1 number, col2 varchar(32))`)
	for i := 1; i <= 3; i++ {
		db.Exec(`insert into my_temp_table values (?, ?)`, i, fmt.Sprintf("test_%v", i))
	}
	rows, err := db.Query(`select col1, col2 from my_temp_table`)
	assertNoError(t, err)
	defer rows.Close()
	var (
		id   int
		name string
	)
	for rows.Next() {
		rows.Scan(&id, &name)
		fmt.Printf("%v - %v\n", id, name)
	}
}

func NewConnection(cfg *gosnowflake.Config) (*sql.DB, error) {
	dsn, err := gosnowflake.DSN(cfg)
	if err != nil {
		return nil, err
	}
	db, err := sql.Open("snowflake", dsn)
	return db, err
}

func NewSnowflakeConfig() *gosnowflake.Config {
	cfg := &gosnowflake.Config{
		Account:   "xxx",
		User:      "ilkin",
		Password:  "xxxx",
		Warehouse: "xxx",
		Role:      "xxxx",
		Params:    make(map[string]*string),
	}
	var keepAlive = "true"
	cfg.Params["client_session_keep_alive"] = &keepAlive
	return cfg
}

func assertNoError(t *testing.T, err error) {
	if err != nil {
		t.Fatalf("unexpected error %v", err)
	}
}
```

### Configuration
driver version : v1.1.9

go version go1.10.2 darwin/amd64

*Server version:* E.g. 1.90.1
```
SELECT CURRENT_VERSION();
CURRENT_VERSION()
-----------------
2.53.1
1 Row(s) produced. Time Elapsed: 1.465s
```

*Client OS:* Mac OS (High Sierra)

**Comment by smtakeda** [comment] 2018-08-09 15:57
Yes, with the current implementation, ensure calling `close` method to avoid the leak.
https://github.com/snowflakedb/gosnowflake/blob/master/connection.go#L171

**Comment by ilkinulas** [comment] 2018-08-09 16:06
Thanks for the reply 
I am using a temporary table so i need to use the same connection across queries.
If I close the connection, is there a way to get the same connection (session) the next time i call `sql.Open`?

**Comment by smtakeda** [comment] 2018-08-09 21:31
So the problem is by default Go SQL will use a connection pool that spins up multiple connections automatically. So if you want to guarantee a single session is used per `sql.Open`, set the parameter as follows:
```
	// single session
	db.SetMaxIdleConns(1)
	db.SetMaxOpenConns(1)
```
See this for example:
https://github.com/snowflakedb/gosnowflake/blob/master/cmd/noconnpool/noconnpool.go#L67

**Comment by ilkinulas** [comment] 2018-08-10 06:25
if I run the sample at  https://github.com/snowflakedb/gosnowflake/blob/master/cmd/noconnpool/noconnpool.go with 
`CLIENT_SESSION_KEEP_ALIVE` enabled 10 heartbeat is started and only one is stopped when `Close` is called. 

By the way `Close` also starts a heartbeat  which is not stopped.

I think, a heartbeat should be associated with a session, not for each `exec` operation on the session.

What do you think?

**Comment by smtakeda** [comment] 2018-08-13 16:48
Merged the fix. @ilkinulas can you please try the latest? Thanks.

**Comment by ilkinulas** [comment] 2018-08-14 06:29
Thanks a lot, I'll try in our test environment and wait for `v1.1.10` to deploy to production.

**Comment by smtakeda** [comment] 2018-08-15 23:03
Thank you for your patience. v1.1.10 was just published.

**Closed** 2018-08-15 23:03 UTC
Labels: bug, question

**Comment by ilkinulas** [comment] 2018-09-10 13:04
Hi, we have upgraded to v1.1.10 and no problems so far.
Thank you.
