### ISSUE TITLE
SNOW-687823: Duplicate/wrong response to queries

### ISSUE THREAD

**Issue by Thomasdezeeuw** [snowflakedb/gosnowflake#683] opened 2022-11-02 10:19 UTC
### Issue description

We have a test suite were we run a number of incorrect queries against Snowflake. For this we create a new (gosnowflake) connection per query, no reuse or sharing. I just saw that two different queries got the same response. For reference the two queries are:
* Session ID: 665762883015854, Query ID: 01a8099b-0000-cc57-0002-5d82001465de, we'll call this "BAD_INT".
* Session ID: 665762883027826, Query ID: 01a8099b-0000-cd4b-0002-5d820014939a, "duplicate alias".

The first response ("BAD_INT") was returned to both queries.

At the moment I can't reproduce this, but since it's a pretty serious bug I did want to report it.

### Example code

I don't think it's relevant, but the queries:

```sql
SELECT 1 FROM schema1.table1 WHERE bad_int = 0 LIMIT 1; // "BAD_INT".

SELECT * FROM schema1.table1, schema1.table1; // "duplicate alias".
```

### Error log

N/A.

### Configuration

*Driver version (or git SHA):* v1.6.13

*Go version:* go version go1.19.2 darwin/arm64

*Server version:* 6.35.1.

*Client OS:* macOS 12.6

**Comment by sfc-gh-dszmolka** [comment] 2022-11-14 09:22
Hi @Thomasdezeeuw 

Thank you for raising this issue and sharing the queryids. Took a peek at both of them, how they were processed and see the following responses from the Snowflake engine:

* 01a8099b-0000-cc57-0002-5d82001465de --> `error 000904, SQL compilation error: error line 1 at position 86 invalid identifier 'BAD_INT'`
* 01a8099b-0000-cd4b-0002-5d820014939a --> `error 002027, SQL compilation error: duplicate alias '<table1>'` `*`
`*` actual table name redacted

Which is i guess the expected behaviour. 

Now, if despite the expected responses from the engine internals, something different is returned to you by the driver that would be indeed be unexpected and thus a problem. 

Since you mentioned you cannot reproduce the issue since then; do you happen to have the gosnowflake driver logs perhaps by any chance from the time when you encountered the issue, or anything which could help in narrowing down the issue to e.g. certain scenarios? Thank you in advance !

**Comment by Thomasdezeeuw** [comment] 2022-11-14 09:55
> Hi @Thomasdezeeuw
> 
> Thank you for raising this issue and sharing the queryids. Took a peek at both of them, how they were processed and see the following responses from the Snowflake engine:
> 
>     * 01a8099b-0000-cc57-0002-5d82001465de --> `error 000904, SQL compilation error: error line 1 at position 86 invalid identifier 'BAD_INT'`
> 
>     * 01a8099b-0000-cd4b-0002-5d820014939a --> `error 002027, SQL compilation error: duplicate alias '<table1>'` `*`
>       `*` actual table name redacted
> 
> 
> Which is i guess the expected behaviour.

Yes, I got the same results in the Snowflake dashboard.

> Now, if despite the expected responses from the engine internals, something different is returned to you by the driver that would be indeed be unexpected and thus a problem.
> 
> Since you mentioned you cannot reproduce the issue since then; do you happen to have the gosnowflake driver logs perhaps by any chance from the time when you encountered the issue, or anything which could help in narrowing down the issue to e.g. certain scenarios? Thank you in advance !

I'm afraid I don't have the logs and I don't remember doing any special to be honest. Just running our test suite, which runs maybe ~16 concurrent queries. Like I said for each test we create a separate gosnowflake connection and close it after we ran the query.

For I think it's best to give this a low priority, I just wanted to share it in case someone else hit the same issue.

**Comment by sfc-gh-dszmolka** [comment] 2022-11-14 10:18
thank you for providing further details on this - agreed, let's keep an eye on this for now and see if you or anyone else hits this again

**Comment by sfc-gh-dszmolka** [comment] 2023-03-29 11:56
no one seems to have hit this for ~5 months now, so I'm closing this issue. it is still available in the repo of course, so anyone can comment on it if they encounter the same issue.

**Closed by sfc-gh-dszmolka** 2023-03-29 11:56 UTC
